server:
  port: 8081

spring:
  mvc.throw-exception-if-no-handler-found: true
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa.hibernate.ddl-auto: none